services:
    broker:
        build:
            context: ./broker
            dockerfile: Dockerfile.api
        ports:
            - "8081:8081"
        volumes:
            - config_data:/root/.kube/karmada.config

    monitor:
        build:
            context: ./monitor
            dockerfile: Dockerfile
        ports:
            - "8082:8082"
    ai-engine:
        build:
            context: ./ai-engine
            dockerfile: Dockerfile.api
        ports:
            - "8083:8083"
    actuator:
        build:
            context: ./actuator
            dockerfile: Dockerfile.api
        ports:
            - "8084:8084"
        volumes:
            - config_data:/root/.kube
    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

networks:
    default:
        name: cloud-ai
        driver: bridge

volumes:
    mongo_data:
    config_data: