services:
    broker:
        container_name: broker
        build:
            context: ./broker
            dockerfile: Dockerfile.api
        volumes:
            - type: bind
              source: ~/.kube/karmada.config
              target: /root/.kube/karmada.config
        network_mode: "host"

    monitor:
        container_name: monitor
        build:
            context: ./monitor
            dockerfile: Dockerfile
        network_mode: host
    ai-engine:
        container_name: ai-engine
        build:
            context: ./ai-engine
            dockerfile: Dockerfile.api
        network_mode: "host"
    actuator:
        container_name: actuator
        build:
            context: ./actuator
            dockerfile: Dockerfile.api
        volumes:
            - type: bind
              source: ~/.kube/karmada.config
              target: /root/.kube/config
            - type: bind
              source: ~/.kwok
              target: /root/.kwok
        network_mode: "host"
    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

networks:
    default:
        name: cloud-ai
        driver: bridge

volumes:
    mongo_data:
    config_data:
