services:
    broker:
        build:
            context: ./broker
            dockerfile: Dockerfile.api
        ports:
            - "8081:8081"
        volumes:
            - type: bind
              source: ~/.kube/karmada.config
              target: /root/.kube/karmada.config
        network_mode: "host"

    monitor:
        build:
            context: ./monitor
            dockerfile: Dockerfile
        network_mode: host
    ai-engine:
        build:
            context: ./ai-engine
            dockerfile: Dockerfile.api
        ports:
            - "8083:8083"
        network_mode: "host"
    actuator:
        build:
            context: ./actuator
            dockerfile: Dockerfile.api
        ports:
            - "8084:8084"
        volumes:
            - type: bind
              source: ~/.kube/karmada.config
              target: /root/.kube/config
            - type: bind
              source: ~/.kwok
              target: /root/.kwok
        network_mode: "host"
    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

networks:
    default:
        name: cloud-ai
        driver: bridge

volumes:
    mongo_data:
    config_data:
